ajoutie minio pour stockie les images des produits

diff --git a/youshop-api/Dockerfile b/youshop-api/Dockerfile
--- a/youshop-api/Dockerfile
+++ b/youshop-api/Dockerfile
@@ -6,7 +6,9 @@ COPY package*.json ./
 RUN npm ci
 
 COPY . .
+RUN npx prisma generate
 RUN npm run build
+RUN ls -la dist/ || echo "dist folder not found!"
 RUN chmod +x start.sh
 
 EXPOSE 3000
